# This is a basic workflow to help you get started with Actions

name: Hello-World Wflow

on: # Controls when the workflow will run
  push: # Triggers the workflow on push or pull request events but only for the "main" branch
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      node-versions:
        description: 'NodeJS version'
        required: true
        default: '20.x'
        type: choice
        options:
          - '16.x'
          - '18.x'
          - '20.x'
      python-versions:
        description: 'Python versions'
        required: true
        default: '3.12'
        type: choice
        options:
          - '3.8'
          - '3.9'
          - '3.10'
      os:
        description: 'Operating System'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - 'ubuntu-latest'
          - 'ubuntu-20.04'
          - 'ubuntu-22.04'
          - 'windows-latest'
          - 'windows-2019'
          - 'windows-2022'
          - 'macos-latest'
          - 'macos-12'
          - 'macos-13'
jobs: # A workflow run is made up of one or more jobs that can run sequentially or in parallel
  job1: # This workflow contains a single job called "build"
    name: job1 hello world
    runs-on: ${{ inputs.os }} # The type of runner that the job will run on

		
    strategy:
      matrix:
        node-version: [${{ inputs['node-versions'] }}]  # Corrección aquí
        python-version: [${{ inputs['python-versions'] }}]  # Corrección aquí

    env:  # the variables are may defined at global or step level
      ENVIRONMENT: develop
      NAME: jhordan
      USERNAME: $ {{ github.actor}}
      
    steps: # Steps represent a sequence of tasks that will be executed as part of the job
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ inputs.node-versions }}
        uses: actions/setup-node@v4.0.4
        with:     
          node-version: ${{ matrix.node-versions }}
          
      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: 3.12        

      - name: Setup Java
      - uses: actions/setup-java@v4
  	with:
    	 distribution: 'temurin' # See 'Supported distributions' for available options
    	 java-version: '21'  
          
      - name: run custom msg # run a one-line scripts -> Runs a single command using the runners shell
        run: | 
          echo "Hello World $NAME, You are in the $ENVIRONMENT environment !!"
          
      - name: run hello-world with nodejs
        run: node index.js

      - name: run HelloWorld.java with Java
        run: java HelloWorld.java

      - name: define variable
        run: echo "USERNAME=${{ GITHUB.ACTOR }}" >> $GITHUB_ENV
      
      - name: run hello-world with python
        run: python hello-world.py
        
      - name:  # run a multi-line script -> Runs a set of commands using the runners shell -> 
        run: |
          echo " *************** PREDIFINED ENVS ***************"
          echo "wf-name -> $GITHUB_WORKFLOW"
          echo "wf-name -> $GITHUB_WORKFLOW"
          echo "build-id -> $GITHUB_RUN_ID"
          echo "run-nbr -> $GITHUB_RUN_NUMBER"
          echo "action-name -> $GITHUB_ACTION"
          echo "event-name -> $GITHUB_EVENT_NAME"
          echo "path-json-trigger -> $GITHUB_EVENT_PATH"
          echo "repo-name -> $GITHUB_REPOSITORY"
          echo "sha-commit -> $GITHUB_SHA"
          echo "head-ref -> $GITHUB_HEAD_REF"
          echo "base-ref -> $GITHUB_BASE_REF"
          echo "user-name -> $GITHUB_ACTOR"
          echo "path-workspace -> $GITHUB_WORKSPACE"
          echo "token-wflow -> $GITHUB_TOKEN"
          echo " *************** SYSTEM ENVS ***************"
          echo "runner-os -> $RUNNER_OS"
          echo "runner-arch -> $RUNNER_ARCH"
          echo "runner-temp-> $RUNNER_TEMP"
          echo "runner-workspace -> $RUNNER_WORKSPACE" 
          echo " *************** GIT ENVS ***************"
          echo "ref-short-name -> $GITHUB_REF_NAME"
          echo "ref-type -> $GITHUB_REF_TYPE"
          echo "ref-head -> $GITHUB_HEAD_REF"
          echo "ref-base -> $GITHUB_BASE_REF"
      
      - name: install dependencies
        run: npm install
      
      - name: build project
        run: npm run build

      - name: deploy app
        run: echo "deploying with NodeJS ${{ matrix.node-versions}} on ${{ inputs.os }}"
          
          
